
### Google login
GET http://localhost:3001/api/auth/google


### Resend otp
POST http://localhost:3001/api/auth/resend-otp
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm90cElkIjoyOSwiaWF0IjoxNzg5OTg1Mzk1LCJleHAiOjE3ODk5ODU5OTV9.kvthvVTCmb18kCsjvOPdb5cUk4SkOGtLddTcj6Bex40



### Verify otp
POST http://localhost:3001/api/auth/verify-otp
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm90cElkIjoyOSwiaWF0IjoxNzg5OTg1Mzk1LCJleHAiOjE3ODk5ODU5OTV9.kvthvVTCmb18kCsjvOPdb5cUk4SkOGtLddTcj6Bex40

{
  "otp": "612186"
}


### Login user
POST http://localhost:3001/api/auth/login 
Content-Type: application/json

{
  "email": "tamilzsurya09@gmail.com",
  "password": "Tmt@2004"
}



### Create user or register user

POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "userName": "tamilarasu",
  "email": "tamilzsurya09@gmail.com",
  "password": "password123",
  "confirmPassword": "password123"
}












### Get all users

GET http://localhost:3001/api/users


### Get one user

GET http://localhost:3001/api/users/1


### Update user

PUT http://localhost:3001/api/users/1
Content-Type: application/json

{
  "fullName": "Tamil Arasu Updated",
  "email": "tamil.updated@example.com"
}


### Delete user

DELETE http://localhost:3001/api/users/1

















### Create habit
POST http://localhost:3001/api/habits
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc4OTk4NTY1MCwiZXhwIjoxNzkwNTkwNDUwfQ.vlB0WqCfIW12562F0RtehNGlcbOdGcokuypLCm7doCU

{
  "name": "Learn React",
  "category": "Health"
}


### Get habits

GET http://localhost:3001/api/habits
Authorization: Bearer YOUR_TOKEN


### Get one habit

GET http://localhost:3001/api/habits/1
Authorization: Bearer YOUR_TOKEN


### Update habit

PUT http://localhost:3001/api/habits/1
Content-Type: application/json
Authorization: Bearer YOUR_TOKEN

{
  "name": "Learn React Advanced",
  "description": "Study advanced React concepts"
}


### Delete habit

DELETE http://localhost:3001/api/habits/1
Authorization: Bearer YOUR_TOKEN
