
### Google login
GET http://localhost:3001/api/auth/google


### Resend otp
POST http://localhost:3001/api/auth/resend-otp
Content-Type: application/json
Authorization: Bearer Your_JWT_Token




### Verify otp
POST http://localhost:3001/api/auth/verify-otp
Content-Type: application/json
Authorization: Bearer Your_JWT_Token

{
  "otp": ""
}


### Login user
POST http://localhost:3001/api/auth/login 
Content-Type: application/json

{
  "email": "",
  "password": ""
}



### Create user or register user

POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "userName": "",
  "email": "",
  "password": "",
  "confirmPassword": ""
}












### Get all users

GET http://localhost:3001/api/users


### Get one user path parameter

GET http://localhost:3001/api/users/1




### Get one user via jwt token

GET http://localhost:3001/api/users/me
Content-Type: application/json
Authorization: Bearer Your_JWT_Token


### Update user

PUT http://localhost:3001/api/users/1
Content-Type: application/json

{
  "fullName": "",
  "email": ""
}


### Delete user

DELETE http://localhost:3001/api/users/1

















### Create habit
POST http://localhost:3001/api/habits
Content-Type: application/json
Authorization: Bearer Your_JWT_Token

{
  "name": "",
  "category": ""
}


### Get All habits

GET http://localhost:3001/api/habits
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc5MTIwNDU1MCwiZXhwIjoxNzkxODA5MzUwfQ.gMWQiXjquw-q_-so112puxG5h1nZtX4q6H-OpCZRqeg

{
  "date": "2026-10-06"
}

### Get one habit

GET http://localhost:3001/api/habits/1
Authorization: Bearer YOUR_TOKEN



### Update habit

PUT http://localhost:3001/api/habits/19
Content-Type: application/json
Authorization: Bearer Your_JWT_Token

{
  "name": "",
  "category": ""
}


### Delete habit

DELETE http://localhost:3001/api/habits/1
Authorization: Bearer Your_JWT_Token









### Habit entries APIs

### Create or Update habit entry

POST http://localhost:3001/api/entries
Content-Type: application/json
Authorization: Bearer Your_JWT_Token

{
  "id": "",
  "habitId": 0,
  "isCompleted": false,
  "entryDate": "2026-09-26"
}














