
### Google login
GET http://localhost:3001/api/auth/google


### Resend otp
POST http://localhost:3001/api/auth/resend-otp
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm90cElkIjoyOSwiaWF0IjoxNzg5OTg1Mzk1LCJleHAiOjE3ODk5ODU5OTV9.kvthvVTCmb18kCsjvOPdb5cUk4SkOGtLddTcj6Bex40



### Verify otp
POST http://localhost:3001/api/auth/verify-otp
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm90cElkIjoxLCJpYXQiOjE3OTEwNzQ1MjIsImV4cCI6MTc5MTA3NTEyMn0.cYw6Wx_JUHf0_2rAFwK542pDUkH24Cr1V-8u1MgQjUo

{
  "otp": "181322"
}


### Login user
POST http://localhost:3001/api/auth/login 
Content-Type: application/json

{
  "email": "tamilzsurya09@yahoo.com",
  "password": "Tmt@2004"
}



### Create user or register user

POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "userName": "Tamil Arasu",
  "email": "tamilzsurya09@yahoo.com",
  "password": "Tmt@2004",
  "confirmPassword": "Tmt@2004"
}












### Get all users

GET http://localhost:3001/api/users


### Get one user path parameter

GET http://localhost:3001/api/users/1




### Get one user via jwt token

GET http://localhost:3001/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc5MDc0MzgyNywiZXhwIjoxNzkxMzQ4NjI3fQ.BuW9uTeERwPjRJ312kjjWZFXfj_tvQasBEmOMFU618o


### Update user

PUT http://localhost:3001/api/users/1
Content-Type: application/json

{
  "fullName": "Tamil Arasu Updated",
  "email": "tamil.updated@example.com"
}


### Delete user

DELETE http://localhost:3001/api/users/1

















### Create habit
POST http://localhost:3001/api/habits
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc4OTk4NTY1MCwiZXhwIjoxNzkwNTkwNDUwfQ.vlB0WqCfIW12562F0RtehNGlcbOdGcokuypLCm7doCU

{
  "name": "Learn React",
  "category": "Health"
}


### Get All habits

GET http://localhost:3001/api/habits
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc5MDgyMTcyOSwiZXhwIjoxNzkxNDI2NTI5fQ.Irox9ycP1SlBJgmASSjIEVpB6-KOwDOfMDzxmEwiqgU


### Get one habit

GET http://localhost:3001/api/habits/1
Authorization: Bearer YOUR_TOKEN


### Update habit

PUT http://localhost:3001/api/habits/19
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc5MDYwMTk3NiwiZXhwIjoxNzkxMjA2Nzc2fQ.N5XMEDYcw0VeH5HcyHJR3PiEsczyjsl1tlsRpegcFT4

{
  "name": "Project Development",
  "category": "Productivity"
}


### Delete habit

DELETE http://localhost:3001/api/habits/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc4OTk4NTY1MCwiZXhwIjoxNzkwNTkwNDUwfQ.vlB0WqCfIW12562F0RtehNGlcbOdGcokuypLCm7doCU









### Habit entries APIs

### Create or Update habit entry

POST http://localhost:3001/api/entries
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc4OTk4NTY1MCwiZXhwIjoxNzkwNTkwNDUwfQ.vlB0WqCfIW12562F0RtehNGlcbOdGcokuypLCm7doCU

{
  "id": "1-2026-09-26",
  "habitId": 1,
  "isCompleted": false,
  "entryDate": "2026-09-26"
}














